[build]
  command = "npx pnpm install && npx pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--shamefully-hoist"
