[build]
  command = "npx pnpm install && npx pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs", "pusher"]

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--shamefully-hoist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "pnpm start"
  targetPort = 3000
  port = 8888
  framework = "#custom"
