[build]
  command = "npx pnpm install && npx pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--shamefully-hoist"
  
[dev]
  framework = "#custom"
  command = "npx pnpm start"
  targetPort = 3000
  port = 8888
  publish = "dist"
